[package]
name = "rust-audio-player"
version = "0.1.0"
authors = ["Viktor Lazarev <taurus101v@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azul = { git = "https://github.com/maps4print/azul", rev = "a6d58ae4fc8e2657981cc510d9f7fbcdc5af0023" }
libpulse-binding = "2"
libpulse-simple-binding = "2"
minimp3 = "0.3"
# sfml = { version = "0.14", default-features = false, features = ["audio"] }
