[package]
name = "oxyfy"
version = "0.0.1"
authors = ["Viktor Lazarev <taurus101v@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.10"

[replace]
"vulkano:0.13.0" = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "85be6295d0cb0a0a4cd405084fa2a71a572a94d7" }
"vulkano-win:0.13.0" = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "85be6295d0cb0a0a4cd405084fa2a71a572a94d7" }
"vulkano-shaders:0.13.0" = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "85be6295d0cb0a0a4cd405084fa2a71a572a94d7" }
"vk-sys:0.4.0" = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "85be6295d0cb0a0a4cd405084fa2a71a572a94d7" }
